export const initPrivacyValue = {
  gender: null,
  year: null,
  city: null,
  area: null,
  familySize: '',
  universityType: null,
  universityCity: null,
  universityName: '',
  department: '',
  departmentGroup: null,
  enrollmentStatus: null,
  sememster: '',
  totalGpa: '',
  previousGpa: '',
  maxGpa: null,
  incomeBracket: null,
  supportIncomeBracket: null,
  monthlyIncome: '',
  socialSupportBracket: null,
};
